### PR TITLE
Fix async handling error and add example resolving from api

### PR DESCRIPTION
**Pull request by oorestisime**
Fix: #14

By doing a for of we assure that the loop runs in sync mode hence gatsby will wait on it. 
Added an example also for fetching from api.

How would you feel if a make some more PRs to port this awesome plugin to gatsby v2?

### CODE REVIEW

**Comment by oorestisime** [comment]
Sorry some auto-formatting got into the way as well. let me know if you want me to clean this up.

**Comment by devdigital** [comment]
Thank you for the feedback, I will review the PR. Work is being done on the next alpha version of the plugin with support for Gatsby 2. Once it is ready, it would be good to get any feedback you have.

**Comment by DonaldWebb** [comment]
Thank you, this save a ton of time. It prevents a race condition where pages data may not be available by the time createPages is run. 
This was causing pages to seemingly randomly not be generated but the data is visible via graphiql as it has completed loading.

**Comment by devdigital** [comment]
These changes are now available in 0.2.2, so closing for now

**Pull request closed without merging**
